require 'highcharts/axis'
require 'highcharts/base'
require 'highcharts/chart'
require 'highcharts/legend'
require 'highcharts/plot_options'
require 'highcharts/rails'
require 'highcharts/series'
require 'highcharts/version'